name: menuapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_datetime_picker:
  file_picker:
  cloud_firestore:
  firebase_core:
  firebase_storage:
  image_picker:
  numberpicker:
  splashscreen:
  flutter_speed_dial:
  polygon_clipper:
  firebase_auth:
  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/des1.jpg
    - assets/images/des2.jpeg
    - assets/images/braids.jpg
    - assets/images/des3.jpg
    - assets/images/monalisa.jpg
    - assets/images/style.jpg
    - assets/images/style2.jpg
    - assets/images/user.jpg
    - assets/images/user2.jpg
    - assets/images/user3.jpg
    - assets/images/chumba.jpg
    - assets/images/coffee.jpg
    - assets/images/Kygo.jpg
    - assets/images/coffee.jpg
    - assets/images/cookies.jpg
    - assets/images/friedchicken.jpg
    - assets/images/friedsteak.jpg
    - assets/images/ribs.jpg
    - assets/images/soup.jpg
    - assets/images/steak.jpg
    - assets/images/tea.jpg
    - assets/images/tomatosoup.jpg
    - assets/images/load.gif
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Quicksand Regular
       fonts:
         - asset: assets/fonts/Quicksand-Regular.ttf
     - family: Raleway
       fonts:
         - asset: assets/fonts/Raleway-Light.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
